const BYTES_PER_KIBIBYTE = 1024
const KIBIBYTES_PER_MEBIBYTE = 1024
const MEBIBYTE = BYTES_PER_KIBIBYTE * KIBIBYTES_PER_MEBIBYTE

const AI_CHAT_MAX_ATTACHMENTS = 5
const AI_CHAT_MAX_ATTACHMENT_SIZE_BYTES = 2 * MEBIBYTE

export { AI_CHAT_MAX_ATTACHMENTS, AI_CHAT_MAX_ATTACHMENT_SIZE_BYTES }
