// Test-only barrel for the retired legacy conversion and mutation flow.
export {
  alignCustomProjectsWithSavedTabs,
  buildCustomProjectUrlIdList,
  buildSanitizedCustomProject,
  buildUncategorizedCustomProject,
  convertCustomProjectToExportUrls,
  convertImportedCustomProjectUrlsToStorage,
  mergeImportedCustomProjects,
  mergeOrderedSubCategories,
  mergeOrderedSubCategoriesWithUncategorized,
  normalizeCategoryKeywords,
  normalizeCustomProjectOrder,
  normalizeImportedCustomProject,
  normalizeImportedCustomProjectsForImport,
  normalizeProjectKeywords,
  normalizeStringArray,
  normalizeSubCategories,
  normalizeSubCategoryOrder,
  normalizeSubCategoryOrderWithUncategorized,
  overwriteImportedCustomProjects,
  resolveImportedCustomProject,
  resolveImportedCustomProjects,
  restoreImportedCustomProjectUrlsFromIds,
  sanitizeCustomProjectMetadata,
  stripCustomProjectUrls,
  toExportCustomProject,
} from './legacy/custom-projects'

export {
  buildBulkUrlRecordMap,
  buildMergedExistingDomainTab,
  buildMergedNewDomainTab,
  buildOverwriteTabs,
  BULK_URL_CONVERSION_THRESHOLD,
  convertTabGroupToExportUrls,
  countAddedCategories,
  countAddedDomains,
  createUnresolvedWarning,
  ensurePlaceholderUrlRecords,
  mergeAiChatConversations,
  mergeCategoryKeywords,
  mergeParentCategoriesData,
  mergeSavedAnalyticsViews,
  mergeSubCategories,
  mergeTabsByDomain,
  mergeUrlData,
  mergeUserSettings,
  normalizeImportedCategory,
  resolveAiChatActiveConversationId,
  resolveImportedTabUrlData,
  resolveMergedAiChatHistory,
  resolveMergedSavedAt,
  resolveOverwriteAiChatHistory,
  shouldImportAiChatHistory,
  shouldImportCustomProjects,
  shouldImportSavedAnalyticsViews,
} from './legacy/settings-merge'

export {
  buildConvertedUrlData,
  convertImportedUrlsToNewFormat,
  convertImportedUrlsWithPreloadedMap,
  CUSTOM_UNCATEGORIZED_PROJECT_ID,
  getPlaceholderUrlTitle,
  getUncategorizedProjectName,
  IMPORT_URL_RECORD_OPTIONS,
  normalizeImportedTabsForImport,
  normalizeUrlKey,
  resolveCurrentLanguage,
  resolveUrlDataForStorage,
  restoreImportedUrlsFromIds,
} from './legacy/url-conversion'

export {
  createCurrentUrlRecordMap,
  createImportedUrlRecordMap,
  downloadAsJson,
  exportSettings,
  importSettings,
  importWithMerge,
  importWithOverwrite,
} from './legacy/LegacyImportExportFlows.fixture'
